[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
lib_extra_dirs = ../esp-common
monitor_speed = 115200
build_flags =
    -Wall
    -Wextra
    -DCORE_DEBUG_LEVEL=1
lib_deps =
    adafruit/Adafruit GFX Library@1.11.11
    adafruit/Adafruit SSD1306@2.5.13
lib_ldf_mode = deep+
