[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
lib_extra_dirs = ../esp-common
monitor_speed = 115200
upload_speed = 115200
build_flags =
    -Wall
    -Wextra
    -DCORE_DEBUG_LEVEL=1
lib_ldf_mode = deep+
